#!/usr/bin/env python3
"""Regenerate the conformance vectors under ../vectors.

The vectors are checked in — this script exists so they are reproducible and
so a bulk edit (a new field, a renamed op) is a one-line change rather than a
hand-edit of several thousand hex characters. Run it from anywhere:

    python3 conformance/tools/gen_vectors.py

then re-run the Go suite (`make test-conformance`) and, on a machine with a
Swift toolchain, `make test-protocol` — the two runners are what actually
decide whether the regenerated bytes are right.

Every literal in here traces to a requirement in docs/spec.md. This file is
NOT a third implementation of the protocol to be consulted at runtime: it is
a fixture builder, and the Go and Swift runners are the implementations under
test.
"""

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.normpath(os.path.join(HERE, "..", "vectors"))

# --------------------------------------------------------------------------
# Small helpers
# --------------------------------------------------------------------------


def h(b: bytes) -> str:
    return b.hex()


def be16(v: int) -> bytes:
    return v.to_bytes(2, "big")


def be32(v: int) -> bytes:
    return v.to_bytes(4, "big")


def be64(v: int) -> bytes:
    return v.to_bytes(8, "big")


def rtp_header(marker: bool, pt: int, seq: int, ts: int, ssrc: int) -> bytes:
    """TS-VID-001: V=2, P=0, X=0, CC=0."""
    return bytes([0x80, (0x80 if marker else 0x00) | (pt & 0x7F)]) + be16(seq) + be32(ts) + be32(ssrc)


def filler(n: int, salt: int = 0) -> bytes:
    """Deterministic, non-repeating-ish payload bytes for the long vectors."""
    return bytes(((i * 7 + salt * 31 + 3) & 0xFF) for i in range(n))


# --------------------------------------------------------------------------
# Reference encodings (docs/spec.md §4, §7, §9, §10)
# --------------------------------------------------------------------------

MAX_RTP_PAYLOAD = 1100  # TS-VID-030
H264_PT = 96
HEVC_PT = 97

CONTROL = {
    "hello": 0x00,
    "keepalive": 0x01,
    "bye": 0x02,
    "pli": 0x03,
    "helloAck": 0x04,
    "serverBye": 0x05,
    "helloPending": 0x06,
    "codecUnsupported": 0x07,
    "helloDenied": 0x08,
    "profileUnsupported": 0x09,
    "nack": 0x0A,
    "receiverReport": 0x0B,
    "ping": 0x0C,
    "fec": 0x0D,
}

TCP_TYPES = {
    "annotation": 0x03,
    "requestToShare": 0x04,
    "shareResponse": 0x05,
    "controlRequest": 0x06,
    "controlGranted": 0x07,
    "controlRevoked": 0x08,
    "inputEvent": 0x09,
    "controlReleased": 0x0A,
    "metadataRequest": 0x0B,
    "metadataResponse": 0x0C,
}


def packetize_h264(nals, ts, ssrc, start_seq):
    """TS-VID-031 / TS-VID-032."""
    packets = []
    seq = start_seq
    for nal in nals:
        if not nal:
            continue
        if len(nal) <= MAX_RTP_PAYLOAD:
            packets.append(rtp_header(False, H264_PT, seq, ts, ssrc) + nal)
            seq = (seq + 1) & 0xFFFF
            continue
        nal_header = nal[0]
        fu_indicator = (nal_header & 0x60) | 28
        nal_type = nal_header & 0x1F
        body = nal[1:]
        frag = MAX_RTP_PAYLOAD - 2
        off, first = 0, True
        while off < len(body):
            take = min(frag, len(body) - off)
            last = off + take == len(body)
            fu_header = nal_type | (0x80 if first else 0) | (0x40 if last else 0)
            packets.append(
                rtp_header(False, H264_PT, seq, ts, ssrc)
                + bytes([fu_indicator, fu_header])
                + body[off : off + take]
            )
            seq = (seq + 1) & 0xFFFF
            off += take
            first = False
    if packets:
        packets[-1] = set_marker(packets[-1])  # TS-VID-006
    return packets


def packetize_hevc(nals, ts, ssrc, start_seq):
    """TS-VID-033 / TS-VID-036."""
    packets = []
    seq = start_seq
    for nal in nals:
        if len(nal) < 2:
            continue
        if len(nal) <= MAX_RTP_PAYLOAD:
            packets.append(rtp_header(False, HEVC_PT, seq, ts, ssrc) + nal)
            seq = (seq + 1) & 0xFFFF
            continue
        nh0, nh1 = nal[0], nal[1]
        original_type = (nh0 >> 1) & 0x3F
        payload_hdr0 = (nh0 & 0x80) | (49 << 1) | (nh0 & 0x01)
        payload_hdr1 = nh1
        body = nal[2:]
        frag = MAX_RTP_PAYLOAD - 3
        off, first = 0, True
        while off < len(body):
            take = min(frag, len(body) - off)
            last = off + take == len(body)
            fu_header = (original_type & 0x3F) | (0x80 if first else 0) | (0x40 if last else 0)
            packets.append(
                rtp_header(False, HEVC_PT, seq, ts, ssrc)
                + bytes([payload_hdr0, payload_hdr1, fu_header])
                + body[off : off + take]
            )
            seq = (seq + 1) & 0xFFFF
            off += take
            first = False
    if packets:
        packets[-1] = set_marker(packets[-1])
    return packets


def set_marker(packet: bytes) -> bytes:
    return packet[:1] + bytes([packet[1] | 0x80]) + packet[2:]


def parity_body(packets):
    """TS-FEC (§9.3): XOR of [len:2][byte1][timestamp:4][payload...]."""
    if len(packets) < 2:
        return b""
    if any(len(p) < 12 for p in packets):
        return b""
    max_len = max(len(p) for p in packets)
    body = bytearray(7 + (max_len - 12))
    for p in packets:
        body[0] ^= (len(p) >> 8) & 0xFF
        body[1] ^= len(p) & 0xFF
        body[2] ^= p[1]
        for i in range(4):
            body[3 + i] ^= p[4 + i]
        for i in range(len(p) - 12):
            body[7 + i] ^= p[12 + i]
    return bytes(body)


def fec_recover(missing_seq, ssrc, members, body):
    """TS-FEC-009 / TS-FEC-010."""
    if len(body) < 7:
        return None
    if any(len(m) < 12 for m in members):
        return None
    if any(len(m) - 12 > len(body) - 7 for m in members):
        return None
    solved = bytearray(body)
    for m in members:
        solved[0] ^= (len(m) >> 8) & 0xFF
        solved[1] ^= len(m) & 0xFF
        solved[2] ^= m[1]
        for i in range(4):
            solved[3 + i] ^= m[4 + i]
        for i in range(len(m) - 12):
            solved[7 + i] ^= m[12 + i]
    recovered_len = int.from_bytes(solved[0:2], "big")
    if recovered_len < 12 or recovered_len - 12 > len(solved) - 7:
        return None
    out = bytearray()
    out.append(0x80)
    out.append(solved[2])
    out += be16(missing_seq)
    out += solved[3:7]
    out += be32(ssrc)
    out += solved[7 : 7 + (recovered_len - 12)]
    return bytes(out)


# --------------------------------------------------------------------------
# Suites
# --------------------------------------------------------------------------


def case(cid, reqs, op, inp, out):
    return {"id": cid, "requirements": reqs, "op": op, "in": inp, "out": out}


def suite_udp_control():
    cases = []

    for name, byte in CONTROL.items():
        cases.append(
            case(
                f"control/encode-{name}",
                ["TS-CTL-001"],
                "control.encodeSimple",
                {"kind": name},
                {"bytes": h(bytes([byte]))},
            )
        )
        cases.append(
            case(
                f"control/decode-{name}",
                ["TS-CTL-001"],
                "control.decodeKind",
                {"bytes": h(bytes([byte]))},
                {"kind": name},
            )
        )

    cases += [
        case(
            "control/decode-unknown-byte",
            ["TS-CTL-002", "TS-EXT-001"],
            "control.decodeKind",
            {"bytes": "0e"},
            {"kind": None},
        ),
        case(
            "control/decode-unknown-high-byte",
            ["TS-CTL-002"],
            "control.decodeKind",
            {"bytes": "7f"},
            {"kind": None},
        ),
        case(
            "control/decode-empty",
            ["TS-GEN-022"],
            "control.decodeKind",
            {"bytes": ""},
            {"kind": None},
        ),
        case(
            "control/classify-empty",
            ["TS-GEN-022"],
            "control.classify",
            {"bytes": ""},
            {"class": "empty"},
        ),
        case(
            "control/classify-rtp-lowest",
            ["TS-GEN-020", "TS-GEN-023"],
            "control.classify",
            {"bytes": "80"},
            {"class": "rtp"},
        ),
        case(
            "control/classify-rtp-highest",
            ["TS-GEN-020"],
            "control.classify",
            {"bytes": "bf"},
            {"class": "rtp"},
        ),
        case(
            "control/classify-control-zero",
            ["TS-GEN-020"],
            "control.classify",
            {"bytes": "00"},
            {"class": "control"},
        ),
        case(
            "control/classify-control-7f",
            ["TS-GEN-021"],
            "control.classify",
            {"bytes": "7f"},
            {"class": "control"},
        ),
        case(
            "control/classify-not-rtp-c0",
            ["TS-GEN-020", "TS-VID-002"],
            "control.classify",
            {"bytes": "c0"},
            {"class": "control"},
        ),
        # HELLO
        case(
            "hello/encode-no-caps",
            ["TS-CAP-006"],
            "hello.encode",
            {"caps": 0},
            {"bytes": "0000"},
        ),
        case(
            "hello/encode-nack-rr-fec",
            ["TS-CAP-001"],
            "hello.encode",
            {"caps": 0x07},
            {"bytes": "0007"},
        ),
        case(
            "hello/decode-legacy-one-byte",
            ["TS-CAP-006"],
            "hello.decodeCaps",
            {"bytes": "00"},
            {"caps": 0},
        ),
        case(
            "hello/decode-extended",
            ["TS-CAP-002"],
            "hello.decodeCaps",
            {"bytes": "0003"},
            {"caps": 3},
        ),
        case(
            "hello/decode-reserved-bits-preserved",
            ["TS-CAP-002"],
            "hello.decodeCaps",
            {"bytes": "00e1"},
            {"caps": 0xE1},
        ),
        case(
            "hello/decode-wrong-first-byte",
            ["TS-CTL-003"],
            "hello.decodeCaps",
            {"bytes": "0103"},
            {"caps": 0},
        ),
        # HELLO_ACK
        case(
            "hello-ack/encode-plain",
            ["TS-CTL-012", "TS-CAP-004"],
            "helloAck.encode",
            {"ssrc": 2, "caps": None},
            {"bytes": h(bytes([0x04]) + be32(2))},
        ),
        case(
            "hello-ack/encode-extended",
            ["TS-CAP-004"],
            "helloAck.encode",
            {"ssrc": 7, "caps": 0x1F},
            {"bytes": h(bytes([0x04]) + be32(7) + bytes([0x1F]))},
        ),
        case(
            "hello-ack/encode-max-ssrc",
            ["TS-AUD-011"],
            "helloAck.encode",
            {"ssrc": 4294967295, "caps": None},
            {"bytes": "04ffffffff"},
        ),
        case(
            "hello-ack/decode-strict-accepts-five",
            ["TS-CAP-004"],
            "helloAck.decodeStrict",
            {"bytes": "0400000002"},
            {"ssrc": 2},
        ),
        case(
            "hello-ack/decode-strict-rejects-six",
            ["TS-CAP-004"],
            "helloAck.decodeStrict",
            {"bytes": "040000000207"},
            {"ssrc": None},
        ),
        case(
            "hello-ack/decode-strict-rejects-four",
            ["TS-CTL-003"],
            "helloAck.decodeStrict",
            {"bytes": "04000000"},
            {"ssrc": None},
        ),
        case(
            "hello-ack/decode-tolerant-five",
            ["TS-CAP-005"],
            "helloAck.decodeTolerant",
            {"bytes": "0400000002"},
            {"ssrc": 2, "caps": 0},
        ),
        case(
            "hello-ack/decode-tolerant-six",
            ["TS-CAP-005"],
            "helloAck.decodeTolerant",
            {"bytes": "040000000218"},
            {"ssrc": 2, "caps": 0x18},
        ),
        case(
            "hello-ack/decode-tolerant-short",
            ["TS-CTL-003"],
            "helloAck.decodeTolerant",
            {"bytes": "0400"},
            {"ssrc": None, "caps": None},
        ),
        case(
            "hello-ack/decode-tolerant-wrong-type",
            ["TS-CTL-003"],
            "helloAck.decodeTolerant",
            {"bytes": "0500000002"},
            {"ssrc": None, "caps": None},
        ),
    ]

    return {
        "suite": "udp-control",
        "description": "Control-datagram demultiplexing, the HELLO/HELLO_ACK handshake, and capability negotiation.",
        "spec": "docs/spec.md#4-udp-control-plane",
        "cases": cases,
    }


def suite_rtp():
    cases = [
        case(
            "rtp/encode-header-video",
            ["TS-VID-001", "TS-GEN-023"],
            "rtp.encodeHeader",
            {"marker": False, "payloadType": 96, "sequenceNumber": 1, "timestamp": 90000, "ssrc": 5},
            {"bytes": h(rtp_header(False, 96, 1, 90000, 5))},
        ),
        case(
            "rtp/encode-header-marker",
            ["TS-VID-006"],
            "rtp.encodeHeader",
            {"marker": True, "payloadType": 97, "sequenceNumber": 65535, "timestamp": 4294967295, "ssrc": 0},
            {"bytes": h(rtp_header(True, 97, 65535, 4294967295, 0))},
        ),
        case(
            "rtp/encode-header-audio-voice",
            ["TS-AUD-003", "TS-AUD-004"],
            "rtp.encodeHeader",
            {"marker": True, "payloadType": 98, "sequenceNumber": 3, "timestamp": 2880, "ssrc": 2},
            {"bytes": h(rtp_header(True, 98, 3, 2880, 2))},
        ),
        case(
            "rtp/encode-header-system-audio",
            ["TS-AUD-004", "TS-AUD-010"],
            "rtp.encodeHeader",
            {"marker": True, "payloadType": 99, "sequenceNumber": 0, "timestamp": 0, "ssrc": 1},
            {"bytes": h(rtp_header(True, 99, 0, 0, 1))},
        ),
        case(
            "rtp/decode-header-plain",
            ["TS-VID-003"],
            "rtp.decodeHeader",
            {"bytes": h(rtp_header(False, 96, 9, 12345, 7) + b"\xaa\xbb")},
            {
                "marker": False,
                "payloadType": 96,
                "sequenceNumber": 9,
                "timestamp": 12345,
                "ssrc": 7,
                "payloadOffset": 12,
            },
        ),
        case(
            "rtp/decode-header-rejects-version-1",
            ["TS-VID-002"],
            "rtp.decodeHeader",
            {"bytes": h(bytes([0x40, 0x60]) + be16(1) + be32(1) + be32(1))},
            {"header": None},
        ),
        case(
            "rtp/decode-header-rejects-short",
            ["TS-VID-003"],
            "rtp.decodeHeader",
            {"bytes": h(bytes([0x80, 0x60]) + be16(1) + be32(1) + b"\x00\x00\x00")},
            {"header": None},
        ),
        case(
            "rtp/decode-header-skips-csrc",
            ["TS-VID-003"],
            "rtp.decodeHeader",
            {
                "bytes": h(
                    bytes([0x82, 0x60]) + be16(4) + be32(8) + be32(9) + be32(0x11111111) + be32(0x22222222) + b"\x01"
                )
            },
            {
                "marker": False,
                "payloadType": 96,
                "sequenceNumber": 4,
                "timestamp": 8,
                "ssrc": 9,
                "payloadOffset": 20,
            },
        ),
        case(
            "rtp/decode-header-skips-extension",
            ["TS-VID-003"],
            "rtp.decodeHeader",
            {
                "bytes": h(
                    bytes([0x90, 0xE1]) + be16(4) + be32(8) + be32(9) + be16(0xBEDE) + be16(2) + be32(0) + be32(0) + b"\x01"
                )
            },
            {
                "marker": True,
                "payloadType": 97,
                "sequenceNumber": 4,
                "timestamp": 8,
                "ssrc": 9,
                "payloadOffset": 24,
            },
        ),
        case(
            "rtp/decode-header-rejects-truncated-extension",
            ["TS-VID-003", "TS-SEC-002"],
            "rtp.decodeHeader",
            {"bytes": h(bytes([0x90, 0x60]) + be16(4) + be32(8) + be32(9) + be16(0xBEDE) + be16(4))},
            {"header": None},
        ),
    ]
    return {
        "suite": "rtp",
        "description": "The fixed RTP header: what a sender emits and what a receiver must tolerate.",
        "spec": "docs/spec.md#71-rtp-header",
        "cases": cases,
    }


def suite_packetization():
    idr_small = bytes([0x65]) + filler(19, 1)
    sps = bytes([0x67]) + filler(11, 2)
    pps = bytes([0x68]) + filler(3, 3)
    idr_big = bytes([0x65]) + filler(2499, 4)
    boundary = bytes([0x65]) + filler(MAX_RTP_PAYLOAD - 1, 5)  # exactly at the limit
    over = bytes([0x65]) + filler(MAX_RTP_PAYLOAD, 6)  # one byte over

    hevc_idr_small = bytes([0x26, 0x01]) + filler(22, 7)
    hevc_vps = bytes([0x40, 0x01]) + filler(10, 8)
    hevc_big = bytes([0x26, 0x01]) + filler(2598, 9)

    cases = [
        case(
            "packetize/h264-single-nal",
            ["TS-VID-031", "TS-VID-006"],
            "packetize.h264",
            {"nals": [h(idr_small)], "timestamp": 3000, "ssrc": 5, "startSequence": 100},
            {"packets": [h(p) for p in packetize_h264([idr_small], 3000, 5, 100)]},
        ),
        case(
            "packetize/h264-parameter-sets-then-idr",
            ["TS-VID-020", "TS-VID-004", "TS-VID-005"],
            "packetize.h264",
            {"nals": [h(sps), h(pps), h(idr_small)], "timestamp": 3000, "ssrc": 5, "startSequence": 65534},
            {"packets": [h(p) for p in packetize_h264([sps, pps, idr_small], 3000, 5, 65534)]},
        ),
        case(
            "packetize/h264-at-payload-limit",
            ["TS-VID-030", "TS-VID-031"],
            "packetize.h264",
            {"nals": [h(boundary)], "timestamp": 1, "ssrc": 2, "startSequence": 0},
            {"packets": [h(p) for p in packetize_h264([boundary], 1, 2, 0)]},
        ),
        case(
            "packetize/h264-one-past-limit-fragments",
            ["TS-VID-030", "TS-VID-032"],
            "packetize.h264",
            {"nals": [h(over)], "timestamp": 1, "ssrc": 2, "startSequence": 0},
            {"packets": [h(p) for p in packetize_h264([over], 1, 2, 0)]},
        ),
        case(
            "packetize/h264-fu-a-three-fragments",
            ["TS-VID-032"],
            "packetize.h264",
            {"nals": [h(idr_big)], "timestamp": 9000, "ssrc": 5, "startSequence": 7},
            {"packets": [h(p) for p in packetize_h264([idr_big], 9000, 5, 7)]},
        ),
        case(
            "packetize/h264-skips-empty-nal",
            ["TS-VID-031"],
            "packetize.h264",
            {"nals": ["", h(idr_small)], "timestamp": 1, "ssrc": 1, "startSequence": 0},
            {"packets": [h(p) for p in packetize_h264([b"", idr_small], 1, 1, 0)]},
        ),
        case(
            "packetize/h264-empty-input",
            ["TS-VID-031"],
            "packetize.h264",
            {"nals": [], "timestamp": 1, "ssrc": 1, "startSequence": 0},
            {"packets": []},
        ),
        case(
            "packetize/hevc-single-nal",
            ["TS-VID-031", "TS-VID-010"],
            "packetize.hevc",
            {"nals": [h(hevc_idr_small)], "timestamp": 3000, "ssrc": 5, "startSequence": 100},
            {"packets": [h(p) for p in packetize_hevc([hevc_idr_small], 3000, 5, 100)]},
        ),
        case(
            "packetize/hevc-parameter-sets-then-idr",
            ["TS-VID-020"],
            "packetize.hevc",
            {"nals": [h(hevc_vps), h(hevc_idr_small)], "timestamp": 3000, "ssrc": 5, "startSequence": 0},
            {"packets": [h(p) for p in packetize_hevc([hevc_vps, hevc_idr_small], 3000, 5, 0)]},
        ),
        case(
            "packetize/hevc-fu-three-fragments",
            ["TS-VID-033"],
            "packetize.hevc",
            {"nals": [h(hevc_big)], "timestamp": 9000, "ssrc": 5, "startSequence": 7},
            {"packets": [h(p) for p in packetize_hevc([hevc_big], 9000, 5, 7)]},
        ),
        case(
            "packetize/hevc-drops-one-byte-nal",
            ["TS-VID-036"],
            "packetize.hevc",
            {"nals": ["26", h(hevc_idr_small)], "timestamp": 1, "ssrc": 1, "startSequence": 0},
            {"packets": [h(p) for p in packetize_hevc([b"\x26", hevc_idr_small], 1, 1, 0)]},
        ),
    ]
    return {
        "suite": "packetization",
        "description": "H.264 (RFC 6184) and HEVC (RFC 7798) packetization, including fragmentation at the 1100-byte payload limit.",
        "spec": "docs/spec.md#74-packetization",
        "cases": cases,
    }


def suite_loss_recovery():
    # --- NACK ------------------------------------------------------------
    entries_one = [(1000, 0x0005)]
    entries_three = [(1, 0), (65535, 0xFFFF), (32768, 0x8001)]
    seventeen = [(i, i) for i in range(17)]

    def nack_bytes(entries):
        out = bytes([0x0A, len(entries)])
        for pid, blp in entries:
            out += be16(pid) + be16(blp)
        return out

    cases = [
        case(
            "nack/encode-single-entry",
            ["TS-NCK-001", "TS-CTL-001"],
            "nack.encode",
            {"entries": [{"pid": p, "blp": b} for p, b in entries_one]},
            {"bytes": h(nack_bytes(entries_one))},
        ),
        case(
            "nack/encode-three-entries",
            ["TS-NCK-001"],
            "nack.encode",
            {"entries": [{"pid": p, "blp": b} for p, b in entries_three]},
            {"bytes": h(nack_bytes(entries_three))},
        ),
        case(
            "nack/encode-truncates-at-sixteen",
            ["TS-NCK-001"],
            "nack.encode",
            {"entries": [{"pid": p, "blp": b} for p, b in seventeen]},
            {"bytes": h(nack_bytes(seventeen[:16]))},
        ),
        case(
            "nack/encode-empty",
            ["TS-NCK-001"],
            "nack.encode",
            {"entries": []},
            {"bytes": "0a00"},
        ),
        case(
            "nack/decode-three-entries",
            ["TS-NCK-001"],
            "nack.decode",
            {"bytes": h(nack_bytes(entries_three))},
            {"entries": [{"pid": p, "blp": b} for p, b in entries_three]},
        ),
        case(
            "nack/decode-rejects-truncated-entry-list",
            ["TS-NCK-002", "TS-SEC-002"],
            "nack.decode",
            {"bytes": h(nack_bytes(entries_three)[:-1])},
            {"entries": []},
        ),
        case(
            "nack/decode-rejects-short-datagram",
            ["TS-CTL-003"],
            "nack.decode",
            {"bytes": "0a"},
            {"entries": []},
        ),
        case(
            "nack/decode-rejects-wrong-type",
            ["TS-CTL-005"],
            "nack.decode",
            {"bytes": h(bytes([0x03, 0x01]) + be16(1) + be16(0))},
            {"entries": []},
        ),
        case(
            "nack/decode-ignores-trailing-bytes",
            ["TS-CTL-004"],
            "nack.decode",
            {"bytes": h(nack_bytes(entries_one) + b"\xde\xad\xbe\xef")},
            {"entries": [{"pid": p, "blp": b} for p, b in entries_one]},
        ),
    ]

    # --- PING ------------------------------------------------------------
    cases += [
        case(
            "ping/encode",
            ["TS-RRP-001"],
            "ping.encode",
            {"serverUptimeNs": "1234567890123456789"},
            {"bytes": h(bytes([0x0C]) + be64(1234567890123456789))},
        ),
        case(
            "ping/encode-zero",
            ["TS-RRP-003"],
            "ping.encode",
            {"serverUptimeNs": "0"},
            {"bytes": "0c0000000000000000"},
        ),
        case(
            "ping/decode",
            ["TS-RRP-002"],
            "ping.decode",
            {"bytes": h(bytes([0x0C]) + be64(18446744073709551615))},
            {"serverUptimeNs": "18446744073709551615"},
        ),
        case(
            "ping/decode-rejects-short",
            ["TS-CTL-003"],
            "ping.decode",
            {"bytes": h(bytes([0x0C]) + b"\x00" * 7)},
            {"serverUptimeNs": None},
        ),
        case(
            "ping/decode-ignores-trailing",
            ["TS-CTL-004"],
            "ping.decode",
            {"bytes": h(bytes([0x0C]) + be64(42) + b"\xff")},
            {"serverUptimeNs": "42"},
        ),
    ]

    # --- Receiver report -------------------------------------------------
    def rr_bytes(frac, ext, jitter, last_ping, delay, fec=None, nack=None):
        out = bytes([0x0B, frac]) + be32(ext) + be32(jitter) + be64(last_ping) + be16(delay)
        if fec is not None:
            out += be16(fec)
        if nack is not None:
            out += be16(nack)
        return out

    legacy = rr_bytes(13, 70000, 900, 1234567890123456789, 17)
    fec_era = rr_bytes(13, 70000, 900, 1234567890123456789, 17, fec=5)
    full = rr_bytes(13, 70000, 900, 1234567890123456789, 17, fec=5, nack=9)

    rr_in = {
        "fracLostQ8": 13,
        "extHighestSeq": 70000,
        "jitterTicks": 900,
        "lastPingTs": "1234567890123456789",
        "delaySincePingMs": 17,
        "fecRecovered": 5,
        "nackRecovered": 9,
    }
    rr_zero_recovery = dict(rr_in, fecRecovered=0, nackRecovered=0)

    cases += [
        case(
            "receiver-report/encode-legacy-20",
            ["TS-RRP-011"],
            "rr.encode",
            {"report": rr_in, "includeRecoveryFields": False},
            {"bytes": h(legacy)},
        ),
        case(
            "receiver-report/encode-extended-24",
            ["TS-RRP-010", "TS-RRP-011"],
            "rr.encode",
            {"report": rr_in, "includeRecoveryFields": True},
            {"bytes": h(full)},
        ),
        case(
            "receiver-report/decode-legacy-20",
            ["TS-RRP-009"],
            "rr.decode",
            {"bytes": h(legacy)},
            {"report": rr_zero_recovery},
        ),
        case(
            "receiver-report/decode-fec-era-22",
            ["TS-RRP-009", "TS-EXT-004"],
            "rr.decode",
            {"bytes": h(fec_era)},
            {"report": dict(rr_in, nackRecovered=0)},
        ),
        case(
            "receiver-report/decode-full-24",
            ["TS-RRP-009"],
            "rr.decode",
            {"bytes": h(full)},
            {"report": rr_in},
        ),
        case(
            "receiver-report/decode-21-reads-as-20",
            ["TS-RRP-009"],
            "rr.decode",
            {"bytes": h(legacy + b"\x07")},
            {"report": rr_zero_recovery},
        ),
        case(
            "receiver-report/decode-23-reads-as-22",
            ["TS-RRP-009"],
            "rr.decode",
            {"bytes": h(fec_era + b"\x07")},
            {"report": dict(rr_in, nackRecovered=0)},
        ),
        case(
            "receiver-report/decode-rejects-19",
            ["TS-CTL-003"],
            "rr.decode",
            {"bytes": h(legacy[:-1])},
            {"report": None},
        ),
        case(
            "receiver-report/decode-rejects-wrong-type",
            ["TS-CTL-005"],
            "rr.decode",
            {"bytes": h(bytes([0x0A]) + legacy[1:])},
            {"report": None},
        ),
        case(
            "receiver-report/no-ping-seen-is-zero",
            ["TS-RRP-003"],
            "rr.encode",
            {
                "report": {
                    "fracLostQ8": 0,
                    "extHighestSeq": 100,
                    "jitterTicks": 0,
                    "lastPingTs": "0",
                    "delaySincePingMs": 0,
                    "fecRecovered": 0,
                    "nackRecovered": 0,
                },
                "includeRecoveryFields": False,
            },
            {"bytes": h(rr_bytes(0, 100, 0, 0, 0))},
        ),
    ]

    # --- FEC datagram framing -------------------------------------------
    body_min = filler(7, 11)
    body_max = filler(1107, 12)
    cases += [
        case(
            "fec/encode-datagram",
            ["TS-CTL-001", "TS-FEC-004"],
            "fec.encodeDatagram",
            {"baseSeq": 1000, "count": 3, "body": h(body_min)},
            {"bytes": h(bytes([0x0D]) + be16(1000) + bytes([3]) + body_min)},
        ),
        case(
            "fec/decode-datagram",
            ["TS-FEC-004"],
            "fec.decodeDatagram",
            {"bytes": h(bytes([0x0D]) + be16(1000) + bytes([3]) + body_min)},
            {"baseSeq": 1000, "count": 3, "body": h(body_min)},
        ),
        case(
            "fec/decode-datagram-max-body",
            ["TS-FEC-003"],
            "fec.decodeDatagram",
            {"bytes": h(bytes([0x0D]) + be16(0) + bytes([16]) + body_max)},
            {"baseSeq": 0, "count": 16, "body": h(body_max)},
        ),
        case(
            "fec/decode-datagram-rejects-oversized-body",
            ["TS-FEC-003", "TS-SEC-003"],
            "fec.decodeDatagram",
            {"bytes": h(bytes([0x0D]) + be16(0) + bytes([16]) + filler(1108, 13))},
            {"baseSeq": None, "count": None, "body": None},
        ),
        case(
            "fec/decode-datagram-rejects-short-body",
            ["TS-FEC-002"],
            "fec.decodeDatagram",
            {"bytes": h(bytes([0x0D]) + be16(0) + bytes([3]) + filler(6, 14))},
            {"baseSeq": None, "count": None, "body": None},
        ),
        case(
            "fec/decode-datagram-rejects-count-1",
            ["TS-FEC-001", "TS-FEC-006"],
            "fec.decodeDatagram",
            {"bytes": h(bytes([0x0D]) + be16(0) + bytes([1]) + body_min)},
            {"baseSeq": None, "count": None, "body": None},
        ),
        case(
            "fec/decode-datagram-rejects-count-17",
            ["TS-FEC-001"],
            "fec.decodeDatagram",
            {"bytes": h(bytes([0x0D]) + be16(0) + bytes([17]) + body_min)},
            {"baseSeq": None, "count": None, "body": None},
        ),
        case(
            "fec/decode-datagram-rejects-count-0",
            ["TS-FEC-001"],
            "fec.decodeDatagram",
            {"bytes": h(bytes([0x0D]) + be16(0) + bytes([0]) + body_min)},
            {"baseSeq": None, "count": None, "body": None},
        ),
    ]

    # --- FEC parity + recovery ------------------------------------------
    p0 = rtp_header(False, 96, 500, 90000, 42) + filler(40, 21)
    p1 = rtp_header(False, 96, 501, 90000, 42) + filler(64, 22)
    p2 = set_marker(rtp_header(False, 96, 502, 90000, 42) + filler(12, 23))
    group = [p0, p1, p2]
    body = parity_body(group)

    cases += [
        case(
            "fec/parity-body-three-packets",
            ["TS-FEC-004"],
            "fec.parity",
            {"packets": [h(p) for p in group]},
            {"body": h(body)},
        ),
        case(
            "fec/parity-body-rejects-single-packet",
            ["TS-FEC-006"],
            "fec.parity",
            {"packets": [h(p0)]},
            {"body": ""},
        ),
        case(
            "fec/parity-body-rejects-short-member",
            ["TS-SEC-002"],
            "fec.parity",
            {"packets": [h(p0), h(p1[:11])]},
            {"body": ""},
        ),
        case(
            "fec/recover-first-member",
            ["TS-FEC-009"],
            "fec.recover",
            {"missingSeq": 500, "ssrc": 42, "members": [h(p1), h(p2)], "body": h(body)},
            {"packet": h(p0)},
        ),
        case(
            "fec/recover-longest-member",
            ["TS-FEC-009", "TS-FEC-010"],
            "fec.recover",
            {"missingSeq": 501, "ssrc": 42, "members": [h(p0), h(p2)], "body": h(body)},
            {"packet": h(p1)},
        ),
        case(
            "fec/recover-marker-packet",
            ["TS-FEC-009", "TS-VID-006"],
            "fec.recover",
            {"missingSeq": 502, "ssrc": 42, "members": [h(p0), h(p1)], "body": h(body)},
            {"packet": h(p2)},
        ),
        case(
            "fec/recover-rejects-short-body",
            ["TS-FEC-002"],
            "fec.recover",
            {"missingSeq": 500, "ssrc": 42, "members": [h(p1), h(p2)], "body": h(body[:6])},
            {"packet": None},
        ),
        case(
            "fec/recover-rejects-short-member",
            ["TS-SEC-002"],
            "fec.recover",
            {"missingSeq": 500, "ssrc": 42, "members": [h(p1[:11]), h(p2)], "body": h(body)},
            {"packet": None},
        ),
        case(
            "fec/recover-rejects-member-past-padded-region",
            ["TS-FEC-010"],
            "fec.recover",
            {
                "missingSeq": 500,
                "ssrc": 42,
                "members": [h(rtp_header(False, 96, 501, 90000, 42) + filler(200, 24))],
                "body": h(body),
            },
            {"packet": None},
        ),
        case(
            "fec/recover-rejects-impossible-length",
            ["TS-FEC-010"],
            "fec.recover",
            {
                "missingSeq": 500,
                "ssrc": 42,
                "members": [],
                "body": h(b"\x00\x0b" + filler(5, 25)),
            },
            {"packet": None},
        ),
    ]

    return {
        "suite": "loss-recovery",
        "description": "NACK, receiver reports, RTT pings, and XOR parity — the capability-negotiated recovery layers.",
        "spec": "docs/spec.md#9-loss-recovery",
        "cases": cases,
    }


def suite_tcp_framing():
    def frame(t, payload=b""):
        return bytes([t]) + be32(len(payload)) + payload

    ann = b'{"type":"clearAll"}'
    req = b'{"fromHostname":"studio-imac"}'

    f_ann = frame(TCP_TYPES["annotation"], ann)
    f_req = frame(TCP_TYPES["requestToShare"], req)
    f_ctlreq = frame(TCP_TYPES["controlRequest"])
    f_unknown = frame(0xFF, b"whatever")
    f_reserved = frame(0x01, b"historical")

    stream = f_ann + f_req + f_ctlreq
    oversize = bytes([TCP_TYPES["annotation"]]) + be32(1048577) + b"\x00" * 8
    at_limit_header = bytes([TCP_TYPES["annotation"]]) + be32(1048576)

    cases = [
        case(
            "tcp/encode-annotation-frame",
            ["TS-TCP-001"],
            "frame.encode",
            {"type": 0x03, "payload": h(ann)},
            {"bytes": h(f_ann)},
        ),
        case(
            "tcp/encode-empty-payload-frame",
            ["TS-TCP-001"],
            "frame.encode",
            {"type": 0x06, "payload": ""},
            {"bytes": h(f_ctlreq)},
        ),
        case(
            "tcp/parse-single-frame",
            ["TS-TCP-006"],
            "frame.parse",
            {"chunks": [h(f_ann)]},
            {"frames": [{"type": 0x03, "payload": h(ann)}], "corrupt": False},
        ),
        case(
            "tcp/parse-three-frames-one-chunk",
            ["TS-TCP-007"],
            "frame.parse",
            {"chunks": [h(stream)]},
            {
                "frames": [
                    {"type": 0x03, "payload": h(ann)},
                    {"type": 0x04, "payload": h(req)},
                    {"type": 0x06, "payload": ""},
                ],
                "corrupt": False,
            },
        ),
        case(
            "tcp/parse-byte-at-a-time",
            ["TS-TCP-006"],
            "frame.parse",
            {"chunks": [h(stream[i : i + 1]) for i in range(len(stream))]},
            {
                "frames": [
                    {"type": 0x03, "payload": h(ann)},
                    {"type": 0x04, "payload": h(req)},
                    {"type": 0x06, "payload": ""},
                ],
                "corrupt": False,
            },
        ),
        case(
            "tcp/parse-partial-header-yields-nothing",
            ["TS-TCP-006"],
            "frame.parse",
            {"chunks": [h(f_ann[:4])]},
            {"frames": [], "corrupt": False},
        ),
        case(
            "tcp/parse-partial-payload-yields-nothing",
            ["TS-TCP-006"],
            "frame.parse",
            {"chunks": [h(f_ann[:-1])]},
            {"frames": [], "corrupt": False},
        ),
        case(
            "tcp/parse-skips-unknown-type",
            ["TS-TCP-003", "TS-EXT-001"],
            "frame.parse",
            {"chunks": [h(f_unknown + f_ann)]},
            {"frames": [{"type": 0x03, "payload": h(ann)}], "corrupt": False},
        ),
        case(
            "tcp/parse-skips-reserved-type",
            ["TS-TCP-003"],
            "frame.parse",
            {"chunks": [h(f_reserved + f_ctlreq)]},
            {"frames": [{"type": 0x06, "payload": ""}], "corrupt": False},
        ),
        case(
            "tcp/parse-rejects-oversized-length",
            ["TS-TCP-004", "TS-SEC-003"],
            "frame.parse",
            {"chunks": [h(oversize)]},
            {"frames": [], "corrupt": True},
        ),
        case(
            "tcp/parse-oversized-poisons-stream",
            ["TS-TCP-005"],
            "frame.parse",
            {"chunks": [h(oversize), h(f_ann)]},
            {"frames": [], "corrupt": True},
        ),
        case(
            "tcp/parse-oversized-rejected-before-buffering",
            ["TS-TCP-004"],
            "frame.parse",
            {"chunks": [h(bytes([0x03]) + be32(0xFFFFFFFF))]},
            {"frames": [], "corrupt": True},
        ),
        case(
            "tcp/parse-accepts-length-at-limit-header",
            ["TS-TCP-004"],
            "frame.parse",
            {"chunks": [h(at_limit_header)]},
            {"frames": [], "corrupt": False},
        ),
        case(
            "tcp/parse-frame-after-unknown-in-same-chunk",
            ["TS-TCP-003", "TS-TCP-007"],
            "frame.parse",
            {"chunks": [h(f_ann + f_unknown + f_req)]},
            {
                "frames": [
                    {"type": 0x03, "payload": h(ann)},
                    {"type": 0x04, "payload": h(req)},
                ],
                "corrupt": False,
            },
        ),
    ]
    return {
        "suite": "tcp-framing",
        "description": "The [type][length][payload] framing shared by annotations, remote control, metadata and request-to-share.",
        "spec": "docs/spec.md#10-the-framed-tcp-channel",
        "cases": cases,
    }


def suite_json_payloads():
    long_host = "h" * 100
    long_reason = "r" * 200
    long_name = "n" * 200

    cases = [
        # --- input events ------------------------------------------------
        case(
            "json/input-mouse-move",
            ["TS-RMT-020"],
            "json.inputEvent.decode",
            {"json": '{"mouseMove":{"x":0.25,"y":0.75}}'},
            {"event": {"kind": "mouseMove", "x": 0.25, "y": 0.75}},
        ),
        case(
            "json/input-mouse-down-with-modifiers",
            ["TS-RMT-021", "TS-RMT-023"],
            "json.inputEvent.decode",
            {"json": '{"mouseDown":{"x":0.5,"y":0.5,"button":"right","modifiers":9}}'},
            {"event": {"kind": "mouseDown", "x": 0.5, "y": 0.5, "button": "right", "modifiers": 9}},
        ),
        case(
            "json/input-mouse-up-middle",
            ["TS-RMT-021"],
            "json.inputEvent.decode",
            {"json": '{"mouseUp":{"x":0.0,"y":1.0,"button":"middle","modifiers":0}}'},
            {"event": {"kind": "mouseUp", "x": 0.0, "y": 1.0, "button": "middle", "modifiers": 0}},
        ),
        case(
            "json/input-scroll",
            ["TS-RMT-028"],
            "json.inputEvent.decode",
            {"json": '{"scroll":{"x":0.5,"y":0.5,"deltaX":0.0,"deltaY":-3.5,"modifiers":1}}'},
            {"event": {"kind": "scroll", "x": 0.5, "y": 0.5, "deltaX": 0.0, "deltaY": -3.5, "modifiers": 1}},
        ),
        case(
            "json/input-key-down-hid-usage",
            ["TS-RMT-022"],
            "json.inputEvent.decode",
            {"json": '{"keyDown":{"key":4,"modifiers":2}}'},
            {"event": {"kind": "keyDown", "key": 4, "modifiers": 2}},
        ),
        case(
            "json/input-key-up-hid-usage",
            ["TS-RMT-022"],
            "json.inputEvent.decode",
            {"json": '{"keyUp":{"key":57,"modifiers":16}}'},
            {"event": {"kind": "keyUp", "key": 57, "modifiers": 16}},
        ),
        case(
            "json/input-rejects-nan",
            ["TS-RMT-029", "TS-SEC-002"],
            "json.inputEvent.decode",
            {"json": '{"mouseMove":{"x":NaN,"y":0.5}}'},
            {"event": None},
        ),
        case(
            "json/input-rejects-infinity",
            ["TS-RMT-029"],
            "json.inputEvent.decode",
            {"json": '{"mouseMove":{"x":Infinity,"y":0.5}}'},
            {"event": None},
        ),
        case(
            "json/input-rejects-out-of-range-literal",
            ["TS-RMT-029"],
            "json.inputEvent.decode",
            {"json": '{"mouseMove":{"x":1e999,"y":0.5}}'},
            {"event": None},
        ),
        case(
            "json/input-rejects-unknown-button",
            ["TS-RMT-021"],
            "json.inputEvent.decode",
            {"json": '{"mouseDown":{"x":0.5,"y":0.5,"button":"thumb","modifiers":0}}'},
            {"event": None},
        ),
        case(
            "json/input-rejects-unknown-case",
            ["TS-TCP-008"],
            "json.inputEvent.decode",
            {"json": '{"teleport":{"x":0.5,"y":0.5}}'},
            {"event": None},
        ),
        case(
            "json/input-rejects-empty-object",
            ["TS-TCP-008"],
            "json.inputEvent.decode",
            {"json": "{}"},
            {"event": None},
        ),
        # --- annotations -------------------------------------------------
        case(
            "json/annotation-add-pen",
            ["TS-ANN-001", "TS-ANN-002", "TS-ANN-004"],
            "json.annotationOp.decode",
            {
                "json": '{"type":"add","annotation":{"id":"6C84FB90-12C4-11E1-840D-7B25C5EE775A",'
                '"tool":"pen","points":[[0.25,0.5],[0.3,0.55]],'
                '"color":{"r":1,"g":0.1,"b":0.15,"a":1},"width":3}}'
            },
            {
                "op": {
                    "kind": "add",
                    "id": "6C84FB90-12C4-11E1-840D-7B25C5EE775A",
                    "tool": "pen",
                    "points": [[0.25, 0.5], [0.3, 0.55]],
                    "color": {"r": 1.0, "g": 0.1, "b": 0.15, "a": 1.0},
                    "width": 3.0,
                }
            },
        ),
        case(
            "json/annotation-add-click-single-point",
            ["TS-ANN-003"],
            "json.annotationOp.decode",
            {
                "json": '{"type":"add","annotation":{"id":"00000000-0000-0000-0000-000000000001",'
                '"tool":"click","points":[[0.1,0.9]],'
                '"color":{"r":0,"g":0,"b":0,"a":1},"width":1}}'
            },
            {
                "op": {
                    "kind": "add",
                    "id": "00000000-0000-0000-0000-000000000001",
                    "tool": "click",
                    "points": [[0.1, 0.9]],
                    "color": {"r": 0.0, "g": 0.0, "b": 0.0, "a": 1.0},
                    "width": 1.0,
                }
            },
        ),
        case(
            "json/annotation-undo",
            ["TS-ANN-004"],
            "json.annotationOp.decode",
            {"json": '{"type":"undo","id":"6C84FB90-12C4-11E1-840D-7B25C5EE775A"}'},
            {"op": {"kind": "undo", "id": "6C84FB90-12C4-11E1-840D-7B25C5EE775A"}},
        ),
        case(
            "json/annotation-clear-all",
            ["TS-ANN-003"],
            "json.annotationOp.decode",
            {"json": '{"type":"clearAll"}'},
            {"op": {"kind": "clearAll"}},
        ),
        case(
            "json/annotation-rejects-unknown-tool",
            ["TS-ANN-003", "TS-TCP-008"],
            "json.annotationOp.decode",
            {
                "json": '{"type":"add","annotation":{"id":"00000000-0000-0000-0000-000000000001",'
                '"tool":"airbrush","points":[[0,0]],'
                '"color":{"r":0,"g":0,"b":0,"a":1},"width":1}}'
            },
            {"op": None},
        ),
        case(
            "json/annotation-rejects-unknown-op",
            ["TS-TCP-008"],
            "json.annotationOp.decode",
            {"json": '{"type":"redo"}'},
            {"op": None},
        ),
        # --- request to share / response ---------------------------------
        case(
            "json/request-to-share",
            ["TS-MET-001"],
            "json.requestToShare.decode",
            {"json": '{"fromHostname":"studio-imac"}'},
            {"fromHostname": "studio-imac"},
        ),
        case(
            "json/request-to-share-clamps-hostname",
            ["TS-TCP-023", "TS-SEC-005"],
            "json.requestToShare.decode",
            {"json": json.dumps({"fromHostname": long_host})},
            {"fromHostname": long_host[:64]},
        ),
        case(
            "json/request-to-share-rejects-missing-field",
            ["TS-TCP-008"],
            "json.requestToShare.decode",
            {"json": "{}"},
            {"fromHostname": None},
        ),
        case(
            "json/share-response-accept",
            ["TS-MET-002"],
            "json.shareResponse.decode",
            {"json": '{"type":"acceptShare"}'},
            {"accepted": True},
        ),
        case(
            "json/share-response-decline",
            ["TS-MET-002"],
            "json.shareResponse.decode",
            {"json": '{"type":"declineShare"}'},
            {"accepted": False},
        ),
        case(
            "json/share-response-rejects-request-payload",
            ["TS-TCP-008"],
            "json.shareResponse.decode",
            {"json": '{"type":"requestToShare","from":"studio-imac"}'},
            {"accepted": None},
        ),
        # --- control revoked ---------------------------------------------
        case(
            "json/control-revoked-reason",
            ["TS-RMT-005"],
            "json.controlRevoked.decode",
            {"json": '{"reason":"the sharer ended remote control"}'},
            {"reason": "the sharer ended remote control"},
        ),
        case(
            "json/control-revoked-empty-payload",
            ["TS-TCP-024"],
            "json.controlRevoked.decode",
            {"json": ""},
            {"reason": ""},
        ),
        case(
            "json/control-revoked-undecodable-payload",
            ["TS-TCP-024"],
            "json.controlRevoked.decode",
            {"json": "not json at all"},
            {"reason": ""},
        ),
        case(
            "json/control-revoked-clamps-reason",
            ["TS-TCP-023", "TS-SEC-005"],
            "json.controlRevoked.decode",
            {"json": json.dumps({"reason": long_reason})},
            {"reason": long_reason[:128]},
        ),
        # --- metadata ----------------------------------------------------
        case(
            "json/metadata-full",
            ["TS-TCP-020", "TS-TCP-021"],
            "json.metadata.decode",
            {
                "json": '{"version":"1.0","shareName":"Display 1","hostname":"studio-imac",'
                '"screenResolution":{"width":3840,"height":2160},"isSharing":true,'
                '"timestamp":776000000,"videoCodec":"hevc"}'
            },
            {
                "metadata": {
                    "version": "1.0",
                    "shareName": "Display 1",
                    "hostname": "studio-imac",
                    "width": 3840,
                    "height": 2160,
                    "isSharing": True,
                    "timestamp": 776000000.0,
                    "videoCodec": "hevc",
                }
            },
        ),
        case(
            "json/metadata-absent-codec-is-null",
            ["TS-TCP-021"],
            "json.metadata.decode",
            {
                "json": '{"version":"1.0","shareName":"","hostname":"box",'
                '"screenResolution":{"width":1280,"height":720},"isSharing":false,'
                '"timestamp":0}'
            },
            {
                "metadata": {
                    "version": "1.0",
                    "shareName": "",
                    "hostname": "box",
                    "width": 1280,
                    "height": 720,
                    "isSharing": False,
                    "timestamp": 0.0,
                    "videoCodec": None,
                }
            },
        ),
        case(
            "json/metadata-clamps-display-strings",
            ["TS-TCP-023", "TS-SEC-005"],
            "json.metadata.decode",
            {
                "json": json.dumps(
                    {
                        "version": "1.0",
                        "shareName": long_name,
                        "hostname": long_name,
                        "screenResolution": {"width": 1, "height": 1},
                        "isSharing": True,
                        "timestamp": 1.5,
                    }
                )
            },
            {
                "metadata": {
                    "version": "1.0",
                    "shareName": long_name[:128],
                    "hostname": long_name[:128],
                    "width": 1,
                    "height": 1,
                    "isSharing": True,
                    "timestamp": 1.5,
                    "videoCodec": None,
                }
            },
        ),
        case(
            "json/metadata-rejects-missing-resolution",
            ["TS-TCP-008"],
            "json.metadata.decode",
            {"json": '{"shareName":"a","hostname":"b","isSharing":true,"timestamp":0}'},
            {"metadata": None},
        ),
    ]
    return {
        "suite": "json-payloads",
        "description": "The JSON payloads carried inside TCP frames, in the decode direction — including the clamps and the rejections that are normative.",
        "spec": "docs/spec.md#102-payload-encodings",
        "cases": cases,
    }


SUITES = [
    suite_udp_control(),
    suite_rtp(),
    suite_packetization(),
    suite_loss_recovery(),
    suite_tcp_framing(),
    suite_json_payloads(),
]


def main():
    os.makedirs(OUT, exist_ok=True)
    index = []
    for suite in SUITES:
        ids = [c["id"] for c in suite["cases"]]
        assert len(ids) == len(set(ids)), f"duplicate case id in {suite['suite']}"
        path = os.path.join(OUT, suite["suite"] + ".json")
        with open(path, "w") as f:
            json.dump(suite, f, indent=2, sort_keys=False)
            f.write("\n")
        index.append({"suite": suite["suite"], "file": suite["suite"] + ".json", "cases": len(ids)})
        print(f"{path}: {len(ids)} cases")

    with open(os.path.join(OUT, "index.json"), "w") as f:
        json.dump(
            {
                "specVersion": 1,
                "spec": "docs/spec.md",
                "generator": "conformance/tools/gen_vectors.py",
                "suites": index,
            },
            f,
            indent=2,
        )
        f.write("\n")
    print(f"total: {sum(s['cases'] for s in index)} cases")


if __name__ == "__main__":
    main()
