#!/usr/bin/env python3
"""Generate the registration-free WinRT application manifest for the
self-contained Windows App SDK layout.

    gen-regfree-manifest.py <framework AppxManifest.xml> <out.manifest> [--verify-dist DIR]

With no framework package registered in the process, RoGetActivationFactory
(which swift-winui calls directly) resolves activatable classes through the
EXE's application manifest. Microsoft's own SelfContained.targets generates
exactly this — every <InProcessServer> registration in the framework MSIX's
AppxManifest.xml (896 classes across 16 DLLs for WinAppSDK 1.5) becomes a
<file><activatableClass/></file> block — and embeds it with mt.exe. This
script is that generation step; the CI job does the mt.exe embed (the manifest
MUST be embedded: an external .manifest file is ignored whenever the exe
already carries an embedded one, and lld-link may embed a default).

Skipping this step does not fail the build — it fails at the user's first
XAML type with REGDB_E_CLASSNOTREG. The generated file must come from the SAME
nupkg version as the staged DLLs; stage-winappsdk.sh calls this in one motion
to keep them in lockstep.

--verify-dist hard-fails if any DLL the manifest references is missing from
the staged directory — a manifest naming an absent DLL is the same silent
first-launch failure in a different coat.
"""

import sys
import xml.etree.ElementTree as ET
from pathlib import Path

APPX_NS = "{http://schemas.microsoft.com/appx/manifest/foundation/windows10}"

# Appx ThreadingModel attribute -> SxS winrt.v1 threadingModel attribute.
THREADING = {"both": "both", "STA": "sta", "MTA": "mta"}


def collect(appx_manifest_path):
    """dll name -> sorted list of (class id, threading model)."""
    tree = ET.parse(appx_manifest_path)
    servers = {}
    for ext in tree.getroot().iter(f"{APPX_NS}InProcessServer"):
        path_el = ext.find(f"{APPX_NS}Path")
        if path_el is None or not path_el.text:
            continue
        dll = path_el.text.strip()
        for cls in ext.findall(f"{APPX_NS}ActivatableClass"):
            name = cls.get("ActivatableClassId")
            threading = THREADING.get(cls.get("ThreadingModel", "both"), "both")
            servers.setdefault(dll, []).append((name, threading))
    return {dll: sorted(set(entries)) for dll, entries in sorted(servers.items())}


def render(servers):
    lines = [
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>',
        # Generated by scripts/windows/gen-regfree-manifest.py — do not edit.
        '<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">',
        '  <assemblyIdentity type="win32" name="Tailscreen.App" version="1.0.0.0"/>',
    ]
    for dll, entries in servers.items():
        lines.append(f'  <file name="{dll}">')
        for name, threading in entries:
            lines.append(
                f'    <activatableClass name="{name}" threadingModel="{threading}"'
                ' xmlns="urn:schemas-microsoft-com:winrt.v1"/>'
            )
        lines.append("  </file>")
    lines.append("</assembly>")
    return "\n".join(lines) + "\n"


def main(argv):
    if len(argv) < 3:
        print(__doc__, file=sys.stderr)
        return 2
    appx, out = Path(argv[1]), Path(argv[2])
    verify_dist = None
    if len(argv) >= 5 and argv[3] == "--verify-dist":
        verify_dist = Path(argv[4])

    servers = collect(appx)
    total = sum(len(v) for v in servers.values())
    if not servers or total < 100:
        # 1.5 carries 896; a near-empty result means the parse silently missed
        # the registrations (schema/namespace drift in a future SDK), which
        # must be a red build, not a manifest with three entries in it.
        print(
            f"suspiciously few activatable classes ({total}) parsed from {appx} — "
            "check the Appx namespace/schema",
            file=sys.stderr,
        )
        return 1

    if verify_dist is not None:
        # Case-insensitive, matching Windows filesystem semantics: the payload
        # ships Microsoft.ui.xaml.dll while the Appx manifest says
        # Microsoft.UI.Xaml.dll, and both are the same file at run time.
        present = {p.name.lower() for p in verify_dist.iterdir() if p.is_file()}
        missing = [dll for dll in servers if dll.lower() not in present]
        if missing:
            print(
                f"manifest references DLLs absent from {verify_dist}: {', '.join(missing)}",
                file=sys.stderr,
            )
            return 1

    text = render(servers)
    ET.fromstring(text)  # well-formedness self-check before anything trusts it
    out.write_text(text, encoding="utf-8")
    print(f"wrote {out}: {total} activatable classes across {len(servers)} DLLs")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
