#!/usr/bin/env python3
"""Generate every Tailscreen brand SVG from one set of geometry constants.

This file is the single source of truth for the mark. Run it via
`make icon-svgs` (or directly: `python3 scripts/gen-marks.py`) after
changing any constant below, then `make icon` / `make icon-windows` /
`make icon-linux` on the matching platform to refresh the derived
binaries (.icns, in-app PDFs, MSIX PNGs, hicolor PNG). Stdlib only —
no pip dependencies.

The mark
--------
A monitor whose outline becomes a fox tail: at the bottom-left the
frame's left arm tapers to a curved tip, a narrow slit of daylight
follows, and the tail itself forms the frame's corner before rising
inside the screen — the original Tailscreen mark's corner-gap gesture,
redrawn with fox-tail anatomy: a belly that swells as it hugs the
bottom of the frame, then a rise whose slim tip CURLS LEFT like a
wave crest. The curl is what reads as tail — a straight rise to a
point reads as a mountain, and a mid-edge notch reads as a path bug
rather than fur (both were tried and rejected). The tail is PART of
the screen outline — that integration, and the little rounded gap
where the outline hands over to the tail, are the identity.

Construction rules that keep the corner joint seamless:
- The frame is an OPEN stroked path: the left arm ends at y=560 with a
  butt cap hidden under ARM_TIP (a filled taper whose top edge sits at
  y=540, inside the arm's painted band x 0..80); the bottom arm ends
  at x=430 hidden under the tail's fill.
- The slit is bounded by ARM_TIP's inner curve and the tail's back
  edge, which run parallel ~28 units apart and exit at the outer
  silhouette. The tail's outer trace starts exactly ON the corner arc
  (its first point must satisfy (x-140)^2+(y-660)^2 = 140^2), or the
  mark grows a lip that pokes outside the frame.
- Any other tail segment not meant to be visible stays inside the
  bezel's painted bands (bottom band y 720..800 for x 140..884).

Three cuts exist, shedding detail as the rendered size drops:

- **Full cut** (`full_mark`): bezel + tail + stand. The primary mark —
  docs/README logo, the Dock-icon glyph, Windows Start tiles, the
  welcome pane. The stand is what makes the shape read as a *monitor*
  rather than a generic rounded rect.
- **Compact cut** (`master_mark`): bezel + tail, no stand — for the
  menubar's pinned 18x18pt box, where the stand would shrink the
  screen. The integrated tail is chunky enough to need no per-size
  reweighting.
- **Solid cut** (`solid_mark`): the screen silhouette filled solid,
  with the screen area knocked out and the tail carved back into the
  knockout (fill-rule evenodd; TAIL_INNER is the tail clipped to the
  screen interior — it must cross the interior boundary exactly at
  its declared points or the corner shows gaps). Small-size artwork:
  the favicon (browser tabs render at 16px, where strokes go
  sub-pixel), the 16/32-point .icns slots, and the Windows 44px/Store
  plate.

Menubar variants share the compact cut's bezel so the three states
(idle / sharing / viewing) keep one silhouette; sharing/viewing use
the plain bezel (no tail) exactly as the mark always has. They are
emitted on a square canvas because the app pins menubar templates to
18x18pt (`loadMenubarTemplate` sets `img.size`); a non-square page
would distort there.

Master coordinate space is 1024x800 for the screen (the bezel stroke's
outer edge lands exactly on the viewBox) plus 154 units of stand below
in the full cut (1024x954 total). Every emitted file is tight-cropped —
consumers add their own padding. (The old assets carried ~50% baked-in
padding, which is why the favicon used to be illegible in a browser
tab.)
"""

import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

GENERATED_NOTE = "Generated by scripts/gen-marks.py - edit the constants there, not this file."

# --- master geometry ---------------------------------------------------------

MASTER_W, MASTER_H = 1024, 800   # the screen (compact cut's whole canvas)
FULL_H = 954                     # screen + stand (full cut's canvas)

# Screen center within the glyph — the optical anchor. The stand hangs below
# it like a descender, so anything placing the full cut centers on *this*,
# not on the bounding box (see `place`).
SCREEN_CY = 400

# Bezel geometry: stroke centered on rect(40,40,944,720) rx=100, width 80
# -> outer edge exactly 0..1024 x 0..800, screen interior 80..944 x 80..720.
# The brand cuts draw it as FRAME_D (open at the bottom-left, where the
# tail takes over); the sharing/viewing menubar states use the closed rect.
BEZEL_RECT = dict(x=40, y=40, w=944, h=720, rx=100, stroke=80)
FRAME_D = ("M 40 560 L 40 140 A 100 100 0 0 1 140 40 "
           "L 884 40 A 100 100 0 0 1 984 140 L 984 660 "
           "A 100 100 0 0 1 884 760 L 430 760")

# The left arm's tapered tip: continues the stroke downward, the inner
# edge sweeping down-left to a softly rounded end just inside the corner
# silhouette — the frame's line "slipping" into becoming the tail.
ARM_TIP = ("M 0 540 L 80 540 L 80 585 "
           "C 80 622 68 650 46 672 "
           "C 34 684 18 690 8 685 "
           "C 2 682 0 678 0 672 Z")

# The fox tail, forming the frame's bottom-left corner. Landmarks: outer
# trace starting on the corner arc at (10,712) and following it around,
# a soft blend off the bottom at x~360, belly swelling to x=456, and the
# tip curling LEFT over the sweep (the two short curves through
# (378,324) and (400,390) are the crest — the outside and inside of the
# curl). The back edge runs parallel to ARM_TIP's inner curve to bound
# the slit.
TAIL = ("M 10 712 "
        "A 140 140 0 0 0 140 800 "
        "L 360 800 "
        "C 395 795 420 765 435 725 "
        "C 452 678 456 620 456 560 "
        "C 456 480 450 424 434 382 "
        "C 422 350 402 330 378 324 "
        "C 392 344 400 366 400 390 "
        "C 396 458 356 532 298 588 "
        "C 248 636 190 664 150 676 "
        "C 122 684 92 692 62 702 "
        "C 42 708 24 712 10 712 Z")

# The tail clipped to the screen interior, traced as part of the screen
# knockout's boundary (solid cut — which keeps a CLOSED corner: the slit
# is ~1px at a 16px favicon and would just be mush). Crossings with the
# interior boundary: (436,720) on the bottom edge, (80,655) on the left
# edge. The curves between the crossings and the curled tip mirror
# TAIL's.
KNOCKOUT = ("M 140 80 H 884 A 60 60 0 0 1 944 140 V 660 A 60 60 0 0 1 884 720 "
            "H 436 "
            "C 450 672 456 618 456 560 "
            "C 456 480 450 424 434 382 "
            "C 422 350 402 330 378 324 "
            "C 392 344 400 366 400 390 "
            "C 396 458 356 532 298 588 "
            "C 248 636 190 664 150 676 "
            "C 124 684 98 672 80 655 "
            "V 140 A 60 60 0 0 1 140 80 Z")

# Solid cut silhouette: the bezel's outer contour as a filled rounded rect
# (radius = bezel rx + stroke/2).
SOLID_RECT = ("M 140 0 H 884 A 140 140 0 0 1 1024 140 V 660 "
              "A 140 140 0 0 1 884 800 H 140 A 140 140 0 0 1 0 660 "
              "V 140 A 140 140 0 0 1 140 0 Z")

# The stand (full cut): bold T — neck overlapping the bezel's bottom edge by
# 4 units (no hairline gap at any raster size) + rounded foot bar. The old
# mark's neck was 6.5% of the screen width and mushed below ~48px; this one
# is ~14% and still reads at 17px.
STAND = ('<rect x="442" y="796" width="140" height="104" fill="{c}"/>'
         '<rect x="277" y="896" width="470" height="58" rx="29" fill="{c}"/>')

# Menubar sharing state: the screen filled solid — visual echo of macOS's
# screen-recording badge. Inset 80 from the screen interior so the gap holds
# at 18pt.
SHARE_FILL = dict(x=160, y=160, w=704, h=480, rx=36)

# Menubar viewing state: play triangle. Bounding box centered on the screen
# interior's center (512, 400) plus a 28-unit rightward optical nudge —
# a box-centered triangle reads left-heavy.
PLAY = "M 391 212 L 689 400 L 391 588 Z"

# --- app-icon tile (1024 x 1024) ---------------------------------------------

# Apple's continuously-cornered rounded rect (Big Sur icon grid: 824x824 tile,
# corner radius 185.4, on a 1024 canvas). NOT an `rx` rect — a circular corner
# changes curvature abruptly where it meets the edge; this one eases into it,
# which is what makes the tile sit right next to native icons. Regenerate with
# scripts/squircle.py rather than by hand.
SQUIRCLE = ("M 100 383.414 C 100 301.807 100 261.003 113.889 217.079 "
            "C 131.344 169.122 169.122 131.344 217.079 113.889 "
            "C 261.003 100 301.807 100 383.414 100 L 640.586 100 "
            "C 722.193 100 762.997 100 806.921 113.889 "
            "C 854.878 131.344 892.656 169.122 910.111 217.079 "
            "C 924 261.003 924 301.807 924 383.414 L 924 640.586 "
            "C 924 722.193 924 762.997 910.111 806.921 "
            "C 892.656 854.878 854.878 892.656 806.921 910.111 "
            "C 762.997 924 722.193 924 640.586 924 L 383.414 924 "
            "C 301.807 924 261.003 924 217.079 910.111 "
            "C 169.122 892.656 131.344 854.878 113.889 806.921 "
            "C 100 762.997 100 722.193 100 640.586 Z")

# The tile is monochrome on purpose — white glyph on near-black, matching the
# Tailscale menubar/app mark it sits next to. The gradient is only there so
# the tile does not read as a flat void against a dark Dock; any hue in it
# would put the two icons out of step.
TILE_GRADIENT = (
    '<defs><linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">'
    '<stop offset="0" stop-color="#2B2B2B"/>'
    '<stop offset="1" stop-color="#101010"/>'
    "</linearGradient></defs>"
)

# Windows plate (Square44x44 / StoreLogo): full-bleed rounded square — subtle
# Win11-style corner, not the macOS squircle, so it doesn't double-plate
# inside Windows' own square tile treatment.
WIN_PLATE_RX = 80

# --- helpers -----------------------------------------------------------------

# Light/dark adaptivity for the docs/README assets: everything draws with
# currentColor and the root color flips with the color scheme. (Safari's
# mask-icon ignores the CSS and just takes the paths, which is fine — it
# supplies its own color.)
ADAPTIVE_STYLE = (
    "<style>:root { color: #000000; } "
    "@media (prefers-color-scheme: dark) { :root { color: #FFFFFF; } }</style>"
)


def comment(text):
    lines = "\n".join(f"  {line}".rstrip() for line in text.strip().splitlines())
    return f"<!--\n{lines}\n-->\n"


def svg(body, viewbox, extra=""):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{viewbox}"{extra}>\n'
            f"{body}\n</svg>\n")


def bezel(color="currentColor"):
    b = BEZEL_RECT
    return (f'<rect x="{b["x"]}" y="{b["y"]}" width="{b["w"]}" height="{b["h"]}" '
            f'rx="{b["rx"]}" fill="none" stroke="{color}" stroke-width="{b["stroke"]}"/>')


def master_mark(color="currentColor"):
    """Compact cut: open frame + arm taper + tail-as-corner, no stand."""
    return (f'<path d="{FRAME_D}" fill="none" stroke="{color}" '
            f'stroke-width="{BEZEL_RECT["stroke"]}" stroke-linecap="butt"/>\n'
            f'<path fill="{color}" d="{ARM_TIP}"/>\n'
            f'<path fill="{color}" d="{TAIL}"/>')


def full_mark(color="currentColor"):
    """Full cut: bezel + tail + stand."""
    return master_mark(color) + "\n" + STAND.format(c=color)


def solid_mark(color="currentColor"):
    """Solid cut: filled silhouette, screen knocked out around the tail."""
    return f'<path fill-rule="evenodd" fill="{color}" d="{SOLID_RECT} {KNOCKOUT}"/>'


def place(glyph, glyph_h, width, canvas_w, canvas_h):
    """Scale `glyph` to `width` and center it on the canvas.

    The full cut is deliberately NOT box-centered: its stand hangs below
    the screen like a descender, so box-centering lands the screen — the
    part the eye reads as the object — well above the canvas center and
    the glyph looks like it is sitting high. Splitting the difference
    between box-centered and screen-centered (same compromise the old
    hand-nudged app icon carried) is what looks centered. For the
    standless cuts glyph_h's center IS the screen center, and the two
    candidates coincide.
    """
    scale = width / MASTER_W
    box_h = glyph_h * scale
    box_top = (canvas_h - box_h) / 2
    screen_top = canvas_h / 2 - SCREEN_CY * scale
    tx = (canvas_w - width) / 2
    ty = (box_top + screen_top) / 2
    return (f'<g transform="translate({tx:g} {ty:g}) scale({scale:g})">\n'
            f"{glyph}\n</g>")


def tile(glyph, glyph_h, width):
    return (TILE_GRADIENT + "\n"
            f'<path d="{SQUIRCLE}" fill="url(#bg)"/>\n'
            + place(glyph, glyph_h, width, 1024, 1024))


def menubar(body):
    # Square canvas, glyph centered vertically: the app pins these templates
    # to 18x18pt, so the page must be square or the glyph distorts.
    pad = (1024 - MASTER_H) / 2
    return svg(f'<g transform="translate(0 {pad:g})">\n{body}\n</g>', "0 0 1024 1024")


# --- files -------------------------------------------------------------------

FILES = {}

FILES["docs/assets/logo.svg"] = comment(f"""
The Tailscreen mark, full cut: bezel with the integrated fox tail +
stand, black/white with the color scheme. Tight viewBox — add padding
at the point of use.
{GENERATED_NOTE}
""") + svg(ADAPTIVE_STYLE + "\n" + full_mark(), f"0 0 {MASTER_W} {FULL_H}")

FILES["docs/assets/favicon.svg"] = comment(f"""
The Tailscreen mark, solid cut: filled screen silhouette with the
screen knocked out around the tail. This is the small-size artwork —
browser tabs render favicons at 16px, where strokes go sub-pixel.
{GENERATED_NOTE}
""") + svg(ADAPTIVE_STYLE + "\n" + solid_mark(), f"0 0 {MASTER_W} {MASTER_H}")

FILES["docs/assets/app-icon.svg"] = comment(f"""
macOS Dock/Finder icon source: the full mark in white, on the standard
Big Sur icon grid (824x824 continuously-cornered tile on a 1024 canvas
— see scripts/squircle.py). Monochrome on purpose: white glyph on
near-black, matching the Tailscale mark it sits next to; the gradient
only keeps the tile from reading as a flat void against a dark Dock.
The glyph is centered on the screen/box compromise, not the bounding
box — the stand is a descender (see gen-marks.py `place`). Rendered by
`make icon`; the 16/32-point slots use app-icon-small.svg instead.
{GENERATED_NOTE}
""") + svg(tile(full_mark("#FFFFFF"), FULL_H, 580), "0 0 1024 1024")

FILES["docs/assets/app-icon-small.svg"] = comment(f"""
Small-slot variant of app-icon.svg: same tile, but the solid cut of
the mark — at 16/32 points the outline cuts' strokes go sub-pixel and
the icon reads as a dark blob. `make icon` renders this into the
16x16 and 32x32 .icns slots (including @2x).
{GENERATED_NOTE}
""") + svg(tile(solid_mark("#FFFFFF"), MASTER_H, 600), "0 0 1024 1024")

FILES["Apps/macOS/Sources/Resources/MenubarIcon.svg"] = comment(f"""
Menubar template glyph, idle state: the brand mark, compact cut — the
bezel with its integrated tail, no stand (which would shrink the
screen in the pinned 18x18pt box). Square canvas for the same pin.
{GENERATED_NOTE}
""") + menubar(master_mark("#000000"))

sf = SHARE_FILL
FILES["Apps/macOS/Sources/Resources/MenubarSharing.svg"] = comment(f"""
Menubar template glyph, actively-sharing state: same bezel as the
brand mark, screen filled solid — visual echo of macOS's
screen-recording badge while keeping the brand silhouette.
{GENERATED_NOTE}
""") + menubar(
    bezel("#000000") + "\n"
    f'<rect x="{sf["x"]}" y="{sf["y"]}" width="{sf["w"]}" height="{sf["h"]}" '
    f'rx="{sf["rx"]}" fill="#000000"/>'
)

FILES["Apps/macOS/Sources/Resources/MenubarViewing.svg"] = comment(f"""
Menubar template glyph, viewing state: same bezel as the brand mark
plus a play triangle — "watching a stream on the Tailscreen screen".
The triangle carries a 28-unit rightward optical nudge; don't recenter
it on the box.
{GENERATED_NOTE}
""") + menubar(bezel("#000000") + "\n" + f'<path fill="#000000" d="{PLAY}"/>')

FILES["Apps/windows/packaging/assets-src/tile-glyph.svg"] = comment(f"""
MSIX Start-tile glyph (Square150x150 / Square310x310): the full mark
in white on transparency — Windows plates tiles with the manifest's
BackgroundColor, so baking a plate in here would double-plate.
{GENERATED_NOTE}
""") + svg(place(full_mark("#FFFFFF"), FULL_H, 640, 1024, 1024), "0 0 1024 1024")

FILES["Apps/windows/packaging/assets-src/tile-glyph-wide.svg"] = comment(f"""
MSIX wide-tile glyph (Wide310x150): same white full mark, centered on
a 310:150 page.
{GENERATED_NOTE}
""") + svg(place(full_mark("#FFFFFF"), FULL_H, 640, 2066, 1000), "0 0 2066 1000")

FILES["Apps/windows/packaging/assets-src/app-plate.svg"] = comment(f"""
MSIX app-list/taskbar icon source (Square44x44 / StoreLogo): solid cut
in white on a full-bleed rounded square — subtle Win11-style corner,
not the macOS squircle, so Windows' own tile treatment doesn't
double-plate it. Solid cut because these render at 44/50px.
{GENERATED_NOTE}
""") + svg(
    TILE_GRADIENT + "\n"
    f'<rect x="0" y="0" width="1024" height="1024" rx="{WIN_PLATE_RX}" fill="url(#bg)"/>\n'
    + place(solid_mark("#FFFFFF"), MASTER_H, 640, 1024, 1024),
    "0 0 1024 1024",
)


def main():
    for rel, content in FILES.items():
        path = os.path.join(REPO, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as fh:
            fh.write(content)
        print(f"wrote {rel}")


if __name__ == "__main__":
    main()
