#!/usr/bin/env python3
"""Generate every Tailscreen brand SVG from one set of geometry constants.

This file is the single source of truth for the mark. Run it via
`make icon-svgs` (or directly: `python3 scripts/gen-marks.py`) after
changing any constant below, then `make icon` / `make icon-windows` /
`make icon-linux` on the matching platform to refresh the derived
binaries (.icns, in-app PDFs, MSIX PNGs, hicolor PNG). Stdlib only —
no pip dependencies.

The mark
--------
A monitor: a screen drawn as one stroked rounded rect (the bezel) with
a Tailscale-nodding "tail" floating inside it, sweeping the screen's
diagonal from a round head at the lower left to a taper at the upper
right, standing on a T-stand (neck + foot). Three cuts exist, shedding
detail as the rendered size drops:

- **Full cut** (`full_mark`): bezel + tail + stand. The primary mark —
  docs/README logo, the Dock-icon glyph, Windows Start tiles, the
  welcome pane. The stand is what makes the shape read as a *monitor*
  rather than a generic rounded rect.
- **Compact cut** (`master_mark`): bezel + tail, no stand. For the
  menubar's pinned 18x18pt box, where the stand would shrink the
  screen and smudge at @1x — and where the sharing/viewing state
  variants need the same silhouette.
- **Solid cut** (`solid_mark`): the screen silhouette filled solid with
  a shorter, fatter tail knocked out of it. Small-size artwork — the
  favicon (browser tabs render at 16px, where strokes go sub-pixel),
  the 16/32-point .icns slots, and the Windows 44px/Store plate. The
  fatter tail exists because the outline tail's taper and thin
  mid-section vanish below ~24px.

Menubar variants share the compact cut's bezel so the three states
(idle / sharing / viewing) keep one silhouette, and are emitted on a
square canvas because the app pins menubar templates to 18x18pt
(`loadMenubarTemplate` sets `img.size`); a non-square page would
distort there.

Master coordinate space is 1024x800 for the screen (the bezel stroke's
outer edge lands exactly on the viewBox) plus 154 units of stand below
in the full cut (1024x954 total). Every emitted file is tight-cropped —
consumers add their own padding. (The old assets carried ~50% baked-in
padding, which is why the favicon used to be illegible in a browser
tab.)
"""

import os

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

GENERATED_NOTE = "Generated by scripts/gen-marks.py - edit the constants there, not this file."

# --- master geometry ---------------------------------------------------------

MASTER_W, MASTER_H = 1024, 800   # the screen (compact cut's whole canvas)
FULL_H = 954                     # screen + stand (full cut's canvas)

# Screen center within the glyph — the optical anchor. The stand hangs below
# it like a descender, so anything placing the full cut centers on *this*,
# not on the bounding box (see `place`).
SCREEN_CY = 400

# Bezel: stroke centered on rect(40,40,944,720) rx=100, width 80 -> outer
# edge exactly 0..1024 x 0..800, screen interior 80..944 x 80..720.
BEZEL_RECT = dict(x=40, y=40, w=944, h=720, rx=100, stroke=80)

# The tail (outline cuts). Floating: >=55 units of clear space to the bezel's
# interior edge on every side, so the gap survives rasterization down to
# ~18px. Round head lower-left, taper to a tip near the screen's upper-right.
TAIL = ("M 800 165 "
        "C 640 390 430 500 240 500 "
        "C 175 500 140 545 140 590 "
        "C 140 640 185 665 245 665 "
        "C 540 665 720 440 800 165 Z")

# The tail (solid cut): shorter and fatter, so the knockout still reads as a
# tail at 16px where the outline tail's taper would dissolve.
TAIL_FAT = ("M 770 200 "
            "C 625 400 435 488 252 488 "
            "C 170 488 130 545 130 602 "
            "C 130 662 192 684 260 680 "
            "C 565 662 705 450 770 200 Z")

# The stand (full cut): bold T — neck overlapping the bezel's bottom edge by
# 4 units (no hairline gap at any raster size) + rounded foot bar. The old
# mark's neck was 6.5% of the screen width and mushed below ~48px; this one
# is ~14% and still reads at 17px.
STAND = ('<rect x="442" y="796" width="140" height="104" fill="{c}"/>'
         '<rect x="277" y="896" width="470" height="58" rx="29" fill="{c}"/>')

# Solid cut silhouette: the bezel's outer contour as a filled rounded rect
# (radius = bezel rx + stroke/2).
SOLID_RECT = ("M 140 0 H 884 A 140 140 0 0 1 1024 140 V 660 "
              "A 140 140 0 0 1 884 800 H 140 A 140 140 0 0 1 0 660 "
              "V 140 A 140 140 0 0 1 140 0 Z")

# Menubar sharing state: the screen filled solid — visual echo of macOS's
# screen-recording badge. Inset 80 from the screen interior so the gap holds
# at 18pt.
SHARE_FILL = dict(x=160, y=160, w=704, h=480, rx=36)

# Menubar viewing state: play triangle. Bounding box centered on the screen
# interior's center (512, 400) plus a 28-unit rightward optical nudge —
# a box-centered triangle reads left-heavy.
PLAY = "M 391 212 L 689 400 L 391 588 Z"

# --- app-icon tile (1024 x 1024) ---------------------------------------------

# Apple's continuously-cornered rounded rect (Big Sur icon grid: 824x824 tile,
# corner radius 185.4, on a 1024 canvas). NOT an `rx` rect — a circular corner
# changes curvature abruptly where it meets the edge; this one eases into it,
# which is what makes the tile sit right next to native icons. Regenerate with
# scripts/squircle.py rather than by hand.
SQUIRCLE = ("M 100 383.414 C 100 301.807 100 261.003 113.889 217.079 "
            "C 131.344 169.122 169.122 131.344 217.079 113.889 "
            "C 261.003 100 301.807 100 383.414 100 L 640.586 100 "
            "C 722.193 100 762.997 100 806.921 113.889 "
            "C 854.878 131.344 892.656 169.122 910.111 217.079 "
            "C 924 261.003 924 301.807 924 383.414 L 924 640.586 "
            "C 924 722.193 924 762.997 910.111 806.921 "
            "C 892.656 854.878 854.878 892.656 806.921 910.111 "
            "C 762.997 924 722.193 924 640.586 924 L 383.414 924 "
            "C 301.807 924 261.003 924 217.079 910.111 "
            "C 169.122 892.656 131.344 854.878 113.889 806.921 "
            "C 100 762.997 100 722.193 100 640.586 Z")

# The tile is monochrome on purpose — white glyph on near-black, matching the
# Tailscale menubar/app mark it sits next to. The gradient is only there so
# the tile does not read as a flat void against a dark Dock; any hue in it
# would put the two icons out of step.
TILE_GRADIENT = (
    '<defs><linearGradient id="bg" x1="0" y1="0" x2="0" y2="1">'
    '<stop offset="0" stop-color="#2B2B2B"/>'
    '<stop offset="1" stop-color="#101010"/>'
    "</linearGradient></defs>"
)

# Windows plate (Square44x44 / StoreLogo): full-bleed rounded square — subtle
# Win11-style corner, not the macOS squircle, so it doesn't double-plate
# inside Windows' own square tile treatment.
WIN_PLATE_RX = 80

# --- helpers -----------------------------------------------------------------

# Light/dark adaptivity for the docs/README assets: everything draws with
# currentColor and the root color flips with the color scheme. (Safari's
# mask-icon ignores the CSS and just takes the paths, which is fine — it
# supplies its own color.)
ADAPTIVE_STYLE = (
    "<style>:root { color: #000000; } "
    "@media (prefers-color-scheme: dark) { :root { color: #FFFFFF; } }</style>"
)


def comment(text):
    lines = "\n".join(f"  {line}".rstrip() for line in text.strip().splitlines())
    return f"<!--\n{lines}\n-->\n"


def svg(body, viewbox, extra=""):
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{viewbox}"{extra}>\n'
            f"{body}\n</svg>\n")


def bezel(color="currentColor"):
    b = BEZEL_RECT
    return (f'<rect x="{b["x"]}" y="{b["y"]}" width="{b["w"]}" height="{b["h"]}" '
            f'rx="{b["rx"]}" fill="none" stroke="{color}" stroke-width="{b["stroke"]}"/>')


def master_mark(color="currentColor"):
    """Compact cut: bezel + tail, no stand."""
    return f'{bezel(color)}\n<path fill="{color}" d="{TAIL}"/>'


def full_mark(color="currentColor"):
    """Full cut: bezel + tail + stand."""
    return master_mark(color) + "\n" + STAND.format(c=color)


def solid_mark(color="currentColor"):
    """Solid cut: screen silhouette with the fat tail knocked out."""
    return f'<path fill-rule="evenodd" fill="{color}" d="{SOLID_RECT} {TAIL_FAT}"/>'


def place(glyph, glyph_h, width, canvas_w, canvas_h):
    """Scale `glyph` to `width` and center it on the canvas.

    The full cut is deliberately NOT box-centered: its stand hangs below
    the screen like a descender, so box-centering lands the screen — the
    part the eye reads as the object — well above the canvas center and
    the glyph looks like it is sitting high. Splitting the difference
    between box-centered and screen-centered (same compromise the old
    hand-nudged app icon carried) is what looks centered. For the
    standless cuts glyph_h's center IS the screen center, and the two
    candidates coincide.
    """
    scale = width / MASTER_W
    box_h = glyph_h * scale
    box_top = (canvas_h - box_h) / 2
    screen_top = canvas_h / 2 - SCREEN_CY * scale
    tx = (canvas_w - width) / 2
    ty = (box_top + screen_top) / 2
    return (f'<g transform="translate({tx:g} {ty:g}) scale({scale:g})">\n'
            f"{glyph}\n</g>")


def tile(glyph, glyph_h, width):
    return (TILE_GRADIENT + "\n"
            f'<path d="{SQUIRCLE}" fill="url(#bg)"/>\n'
            + place(glyph, glyph_h, width, 1024, 1024))


def menubar(body):
    # Square canvas, glyph centered vertically: the app pins these templates
    # to 18x18pt, so the page must be square or the glyph distorts.
    pad = (1024 - MASTER_H) / 2
    return svg(f'<g transform="translate(0 {pad:g})">\n{body}\n</g>', "0 0 1024 1024")


# --- files -------------------------------------------------------------------

FILES = {}

FILES["docs/assets/logo.svg"] = comment(f"""
The Tailscreen mark, full cut: bezel + tail + stand, black/white with
the color scheme. Tight viewBox — add padding at the point of use.
{GENERATED_NOTE}
""") + svg(ADAPTIVE_STYLE + "\n" + full_mark(), f"0 0 {MASTER_W} {FULL_H}")

FILES["docs/assets/favicon.svg"] = comment(f"""
The Tailscreen mark, solid cut: screen silhouette with the tail
knocked out. This is the small-size artwork — browser tabs render
favicons at 16px, where the outline cuts' strokes go sub-pixel.
{GENERATED_NOTE}
""") + svg(ADAPTIVE_STYLE + "\n" + solid_mark(), f"0 0 {MASTER_W} {MASTER_H}")

FILES["docs/assets/app-icon.svg"] = comment(f"""
macOS Dock/Finder icon source: the full mark in white, on the standard
Big Sur icon grid (824x824 continuously-cornered tile on a 1024 canvas
— see scripts/squircle.py). Monochrome on purpose: white glyph on
near-black, matching the Tailscale mark it sits next to; the gradient
only keeps the tile from reading as a flat void against a dark Dock.
The glyph is centered on the screen/box compromise, not the bounding
box — the stand is a descender (see gen-marks.py `place`). Rendered by
`make icon`; the 16/32-point slots use app-icon-small.svg instead.
{GENERATED_NOTE}
""") + svg(tile(full_mark("#FFFFFF"), FULL_H, 580), "0 0 1024 1024")

FILES["docs/assets/app-icon-small.svg"] = comment(f"""
Small-slot variant of app-icon.svg: same tile, but the solid cut of
the mark — at 16/32 points the outline cuts' strokes go sub-pixel and
the icon reads as a dark blob. `make icon` renders this into the
16x16 and 32x32 .icns slots (including @2x).
{GENERATED_NOTE}
""") + svg(tile(solid_mark("#FFFFFF"), MASTER_H, 600), "0 0 1024 1024")

FILES["Apps/macOS/Sources/Resources/MenubarIcon.svg"] = comment(f"""
Menubar template glyph, idle state: the brand mark, compact cut — no
stand, which would shrink the screen and smudge in the pinned 18x18pt
box. Square canvas for the same pin.
{GENERATED_NOTE}
""") + menubar(master_mark("#000000"))

sf = SHARE_FILL
FILES["Apps/macOS/Sources/Resources/MenubarSharing.svg"] = comment(f"""
Menubar template glyph, actively-sharing state: same bezel as the
brand mark, screen filled solid — visual echo of macOS's
screen-recording badge while keeping the brand silhouette.
{GENERATED_NOTE}
""") + menubar(
    bezel("#000000") + "\n"
    f'<rect x="{sf["x"]}" y="{sf["y"]}" width="{sf["w"]}" height="{sf["h"]}" '
    f'rx="{sf["rx"]}" fill="#000000"/>'
)

FILES["Apps/macOS/Sources/Resources/MenubarViewing.svg"] = comment(f"""
Menubar template glyph, viewing state: same bezel as the brand mark
plus a play triangle — "watching a stream on the Tailscreen screen".
The triangle carries a 28-unit rightward optical nudge; don't recenter
it on the box.
{GENERATED_NOTE}
""") + menubar(bezel("#000000") + "\n" + f'<path fill="#000000" d="{PLAY}"/>')

FILES["Apps/windows/packaging/assets-src/tile-glyph.svg"] = comment(f"""
MSIX Start-tile glyph (Square150x150 / Square310x310): the full mark
in white on transparency — Windows plates tiles with the manifest's
BackgroundColor, so baking a plate in here would double-plate.
{GENERATED_NOTE}
""") + svg(place(full_mark("#FFFFFF"), FULL_H, 640, 1024, 1024), "0 0 1024 1024")

FILES["Apps/windows/packaging/assets-src/tile-glyph-wide.svg"] = comment(f"""
MSIX wide-tile glyph (Wide310x150): same white full mark, centered on
a 310:150 page.
{GENERATED_NOTE}
""") + svg(place(full_mark("#FFFFFF"), FULL_H, 640, 2066, 1000), "0 0 2066 1000")

FILES["Apps/windows/packaging/assets-src/app-plate.svg"] = comment(f"""
MSIX app-list/taskbar icon source (Square44x44 / StoreLogo): solid cut
in white on a full-bleed rounded square — subtle Win11-style corner,
not the macOS squircle, so Windows' own tile treatment doesn't
double-plate it. Solid cut because these render at 44/50px.
{GENERATED_NOTE}
""") + svg(
    TILE_GRADIENT + "\n"
    f'<rect x="0" y="0" width="1024" height="1024" rx="{WIN_PLATE_RX}" fill="url(#bg)"/>\n'
    + place(solid_mark("#FFFFFF"), MASTER_H, 640, 1024, 1024),
    "0 0 1024 1024",
)


def main():
    for rel, content in FILES.items():
        path = os.path.join(REPO, rel)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "w") as fh:
            fh.write(content)
        print(f"wrote {rel}")


if __name__ == "__main__":
    main()
